- name: Deploy Apache2 Static Website
  hosts: web
  become: yes

  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Copy website files
      copy:
        src: site/
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Start and enable apache2
      service:
        name: apache2
        state: started
        enabled: yes
